import * as T from 'three';
import './styles.css';

type Biome='underwater'|'woodland'|'sky';
type FieldObject={name:string;icon:string;kind:'animal'|'plant';biome:Biome;fact:string;question:string;choices:string[];answer:number;object:T.Group;home:T.Vector3;phase:number};
type VisitorProfile={name:string;interests:string;style:string};

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`
  <main class="world" id="world"><div class="noise"></div></main>
  <header class="brand"><div class="brand-mark">N</div><div><strong>Inside Nature</strong><small>Living field atlas · 01</small></div></header>
  <div class="top-status"><span class="ai-status" id="ai-status">Personal guide ready</span><span class="live">Ecosystem live</span><button class="sound" id="sound" aria-label="Toggle ambient sound">♪</button></div>
  <aside class="biome-card"><div class="eyebrow" id="zone-code">Biome 02 · Temperate</div><h2 id="zone-name">Woodland</h2><p id="zone-copy">Follow the river, listen closely, and meet the lives that keep this forest in balance.</p><div class="progress-label"><span>Field journal</span><span id="progress-count">0 / 0</span></div><div class="progress-track"><i id="progress-bar"></i></div><div class="discoveries" id="discoveries"></div></aside>
  <nav class="depth-nav" aria-label="Travel between biomes"><button data-biome="sky">⌁<span>Canopy & sky</span></button><i></i><button data-biome="woodland" class="active">♧<span>Forest floor</span></button><i></i><button data-biome="underwater">≋<span>Below the surface</span></button></nav>
  <div class="crosshair"></div><div class="interact-hint" id="hint"><b>E</b><span></span></div>
  <div class="controls"><div class="keys"><b class="key">W</b><b class="key">A</b><b class="key">S</b><b class="key">D</b></div><span>Move</span><div class="keys"><b class="key">Space</b><b class="key">Shift</b></div><span>Rise / descend</span><div class="keys"><b class="key">Click</b><b class="key">E</b></div><span>Discover</span></div>
  <div class="altitude"><b id="altitude">+03.5 m</b><span>Relative depth</span></div>
  <section class="intro" id="intro"><div class="intro-inner"><div class="kicker">A living world, explained for you</div><h1>Step <em>inside.</em></h1><p class="intro-copy" id="intro-copy">Tell your NVIDIA-powered field guide what sparks your curiosity. It will shape the welcome and each discovery around you.</p><form class="profile" id="profile"><label><span>What should we call you?</span><input id="visitor-name" maxlength="40" placeholder="Explorer" autocomplete="given-name"></label><label><span>What are you curious about?</span><input id="visitor-interests" maxlength="240" placeholder="food webs, big cats, climate…"></label><label><span>How should we explain?</span><select id="visitor-style"><option value="curious">Curious & vivid</option><option value="simple">Simple & concise</option><option value="scientific">Scientific</option><option value="storylike">Like a nature story</option></select></label><button class="begin" id="begin" type="submit"><span>Personalize my journey</span><i>→</i></button><small class="profile-note" id="profile-note">Works with a graceful local fallback when NVIDIA NIM is not configured.</small></form></div></section>
  <section class="dialogue" id="dialogue" aria-modal="true" role="dialog"><article class="dialogue-card"><button class="dialogue-close" id="dialogue-close" aria-label="Close">×</button><div class="dialogue-tag" id="dialogue-tag"></div><div class="dialogue-heading"><h3 id="dialogue-name"></h3><span class="nim-badge" id="nim-badge">Field guide</span></div><p id="dialogue-fact"></p><div class="choices" id="choices"></div><p class="result" id="result"></p></article></section>`;

const world=document.querySelector<HTMLElement>('#world')!;
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;world.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#91c7c8');scene.fog=new T.FogExp2('#8bb8a7',.018);
const camera=new T.PerspectiveCamera(65,innerWidth/innerHeight,.05,160);camera.position.set(0,3.5,15);

const hemi=new T.HemisphereLight(0xc6e9f2,0x23452f,2.3);scene.add(hemi);
const sun=new T.DirectionalLight(0xffe8ac,3.2);sun.position.set(-18,28,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;scene.add(sun);

const mat=(color:T.ColorRepresentation,roughness=.82)=>new T.MeshStandardMaterial({color,roughness,metalness:0});
const mesh=(geometry:T.BufferGeometry,material:T.Material,cast=true)=>{const value=new T.Mesh(geometry,material);value.castShadow=cast;value.receiveShadow=true;return value;};
const sphere=(r:number,color:T.ColorRepresentation)=>mesh(new T.SphereGeometry(r,18,12),mat(color));
const box=(x:number,y:number,z:number,color:T.ColorRepresentation)=>mesh(new T.BoxGeometry(x,y,z),mat(color));
const cylinder=(top:number,bottom:number,height:number,color:T.ColorRepresentation,segments=10)=>mesh(new T.CylinderGeometry(top,bottom,height,segments),mat(color));
let seed=481516;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};

// Forest floor and winding river, based on the visual layers of the supplied illustration.
const leftLand=box(30.5,1.2,66,'#527849'),rightLand=box(26.5,1.2,66,'#527849');leftLand.position.set(-19.75,-.65,0);rightLand.position.set(21.75,-.65,0);scene.add(leftLand,rightLand);
const riverMaterial=new T.MeshPhysicalMaterial({color:'#45baca',transparent:true,opacity:.78,roughness:.18,metalness:.05,transmission:.12,side:T.DoubleSide});
const river=new T.Mesh(new T.PlaneGeometry(13,66,12,22),riverMaterial);river.rotation.x=-Math.PI/2;river.rotation.z=-.08;river.position.set(2,.025,0);scene.add(river);
const bankMat=mat('#ad8d55');for(const side of[-1,1]){const bank=box(.7,.25,65,'#b08a50');bank.position.set(2+side*6.5,.03,0);bank.rotation.y=.08;scene.add(bank)}
const bridge=new T.Group();for(let i=-4;i<=4;i++){const plank=box(1.1,.16,2.8,'#9a6338');plank.position.set(i*1.02,.55,2);plank.rotation.z=Math.sin(i*.45)*.045;bridge.add(plank)}for(const z of[.85,3.15]){const rail=box(10,.12,.12,'#774729');rail.position.set(0,1.18,z);bridge.add(rail)}bridge.position.set(2,0,0);scene.add(bridge);

function tree(x:number,z:number,scale:number){const g=new T.Group();const trunk=cylinder(.28,.42,3.7,'#66452d',9);trunk.position.y=1.8;g.add(trunk);for(const [y,r,c] of [[3.2,1.9,'#2f6741'],[4.25,1.55,'#3f7b49'],[5.15,1.05,'#4c8b50']] as [number,number,string][]){const crown=mesh(new T.ConeGeometry(r,2.7,10),mat(c));crown.position.y=y;g.add(crown)}g.position.set(x,0,z);g.scale.setScalar(scale);scene.add(g);return g}
for(let i=0;i<42;i++){let x=(random()-.5)*58,z=(random()-.5)*58;if(Math.abs(x-2)<8)x+=x<2?-8:8;tree(x,z,.72+random()*.65)}
for(let i=0;i<90;i++){const blade=mesh(new T.ConeGeometry(.08,.6+random()*.5,5),mat(random()>.4?'#6f984e':'#92aa50'),false);blade.position.set((random()-.5)*56,.3,(random()-.5)*56);scene.add(blade)}
for(let i=0;i<28;i++){const flower=new T.Group();const stem=cylinder(.025,.025,.5,'#48733d',5);stem.position.y=.25;flower.add(stem);for(let p=0;p<5;p++){const petal=sphere(.09,random()>.5?'#f5d7dc':'#f4dd73');petal.scale.set(1.6,.55,1);petal.position.set(Math.cos(p*1.256)*.12,.53,Math.sin(p*1.256)*.12);flower.add(petal)}flower.position.set((random()-.5)*46,0,(random()-.5)*46);scene.add(flower)}

// Underwater world.
const seabed=mesh(new T.CylinderGeometry(34,35,1,48),mat('#3d7770'),false);seabed.position.y=-11.5;scene.add(seabed);
for(let i=0;i<45;i++){const rock=sphere(.25+random()*.7,random()>.5?'#517a74':'#8c8c72');rock.scale.set(1.3,.55,1);rock.position.set((random()-.5)*48,-10.7,(random()-.5)*48);scene.add(rock)}
for(let i=0;i<35;i++){const weed=mesh(new T.ConeGeometry(.09+random()*.08,1+random()*2,7),mat(random()>.5?'#2d8771':'#6aa764'),false);weed.position.set((random()-.5)*45,-10+random()*.4,(random()-.5)*45);weed.rotation.z=(random()-.5)*.25;scene.add(weed)}
const bubbles:T.Mesh[]=[];for(let i=0;i<42;i++){const bubble=new T.Mesh(new T.SphereGeometry(.04+random()*.08,8,6),new T.MeshBasicMaterial({color:'#c8f5ed',transparent:true,opacity:.5,wireframe:true}));bubble.position.set((random()-.5)*45,-10+random()*9,(random()-.5)*45);bubble.userData.speed=.25+random()*.5;bubbles.push(bubble);scene.add(bubble)}

// Sky landmarks.
const cloudMaterial=new T.MeshStandardMaterial({color:'#fff7df',roughness:1,transparent:true,opacity:.87});
for(let i=0;i<13;i++){const cloud=new T.Group();for(let j=0;j<5;j++){const puff=new T.Mesh(new T.SphereGeometry(1.2+random(),12,8),cloudMaterial);puff.scale.y=.55;puff.position.set(j*1.35+(random()-.5),random()*.6,(random()-.5)*1.4);cloud.add(puff)}cloud.position.set((random()-.5)*58,13+random()*13,(random()-.5)*58);scene.add(cloud)}

function animalBody(color:string,accent:string){const g=new T.Group();const body=sphere(.65,color);body.scale.set(1.35,.78,.72);body.rotation.y=Math.PI/2;g.add(body);const head=sphere(.43,color);head.position.set(0,.37,-.78);g.add(head);const eye=sphere(.055,'#101b17');eye.position.set(.3,.48,-1.12);g.add(eye);const eye2=eye.clone();eye2.position.x=-.3;g.add(eye2);const nose=sphere(.1,accent);nose.position.set(0,.28,-1.18);g.add(nose);return g}
function deer(){const g=animalBody('#a86a35','#33251d');g.scale.setScalar(.85);for(const x of[-.4,.4])for(const z of[-.3,.35]){const leg=cylinder(.07,.09,1.2,'#74472d',7);leg.position.set(x,-.72,z);g.add(leg)}for(const x of[-.23,.23]){const antler=cylinder(.035,.055,.8,'#d2b27b',6);antler.position.set(x,1,-.85);antler.rotation.z=x*1.5;g.add(antler)}return g}
function fox(){const g=animalBody('#c55e32','#342018');for(const x of[-.42,.42]){const ear=mesh(new T.ConeGeometry(.2,.55,5),mat('#9e432b'));ear.position.set(x,.9,-.77);g.add(ear)}const tail=mesh(new T.ConeGeometry(.35,1.8,9),mat('#d87542'));tail.rotation.x=-Math.PI/2;tail.position.set(0,.15,1.25);g.add(tail);return g}
function rabbit(){const g=animalBody('#9b8f7d','#594b42');g.scale.setScalar(.65);for(const x of[-.2,.2]){const ear=sphere(.18,'#a79c8c');ear.scale.set(1,2.8,.6);ear.position.set(x,1,-.72);g.add(ear)}return g}
function fish(color:string){const g=new T.Group();const body=sphere(.62,color);body.scale.set(1.55,.72,.45);g.add(body);const tail=mesh(new T.ConeGeometry(.55,1,3),mat(color));tail.rotation.z=-Math.PI/2;tail.position.x=-1.15;g.add(tail);const eye=sphere(.07,'#101b17');eye.position.set(.68,.2,.35);g.add(eye);return g}
function turtle(){const g=new T.Group();const shell=sphere(.7,'#527945');shell.scale.set(1.25,.45,1);g.add(shell);const head=sphere(.3,'#7aa068');head.position.x=1;g.add(head);for(const z of[-.65,.65])for(const x of[-.45,.45]){const fin=mesh(new T.ConeGeometry(.18,.65,5),mat('#71935f'));fin.rotation.z=Math.PI/2;fin.position.set(x,0,z);g.add(fin)}return g}
function ray(){const g=new T.Group();const wing=mesh(new T.SphereGeometry(.9,18,8),mat('#487b84'));wing.scale.set(1.7,.16,1);g.add(wing);const tail=cylinder(.03,.07,2.3,'#365e65',7);tail.rotation.z=Math.PI/2;tail.position.x=-1.6;g.add(tail);return g}
function bird(color:string){const g=new T.Group();const body=sphere(.35,color);body.scale.set(.75,.65,1.45);g.add(body);for(const side of[-1,1]){const wing=mesh(new T.ConeGeometry(.55,1.8,3),mat(color));wing.rotation.z=side*Math.PI/2;wing.position.x=side*.85;g.add(wing)}const beak=mesh(new T.ConeGeometry(.12,.5,5),mat('#e5b047'));beak.rotation.x=Math.PI/2;beak.position.z=-.7;g.add(beak);return g}
function butterfly(){const g=new T.Group();const body=cylinder(.06,.08,.65,'#2c211b',7);body.rotation.x=Math.PI/2;g.add(body);for(const side of[-1,1]){const wing=sphere(.38,side<0?'#e5903c':'#efb24c');wing.scale.set(.22,1,1.2);wing.position.x=side*.27;g.add(wing)}return g}
function tiger(){const g=animalBody('#d97827','#26180f');g.scale.setScalar(1.18);for(const x of[-.5,.5])for(const z of[-.3,.35]){const leg=cylinder(.1,.13,1.25,'#d97827',7);leg.position.set(x,-.78,z);g.add(leg)}for(let i=-2;i<=2;i++){const stripe=box(.07,.48,.72,'#2b2019');stripe.position.set(i*.25,.28,.05);stripe.rotation.z=i*.1;g.add(stripe)}for(const x of[-.27,.27]){const ear=mesh(new T.ConeGeometry(.2,.45,5),mat('#2b2019'));ear.position.set(x,.88,-.82);g.add(ear)}return g}
function frog(){const g=new T.Group();const body=sphere(.42,'#5d9b48');body.scale.set(1,.65,1.15);g.add(body);for(const x of[-.28,.28]){const eye=sphere(.14,'#9bc66c');eye.position.set(x,.34,-.25);g.add(eye);const pupil=sphere(.05,'#172418');pupil.position.set(x,.38,-.37);g.add(pupil)}for(const x of[-.5,.5]){const leg=box(.55,.12,.16,'#4f873e');leg.position.set(x,-.18,.22);g.add(leg)}return g}
function owl(){const g=new T.Group();const body=sphere(.55,'#8b7257');body.scale.set(.8,1.2,.72);g.add(body);for(const x of[-.2,.2]){const eye=sphere(.15,'#e6c35a');eye.position.set(x,.2,-.48);g.add(eye);const pupil=sphere(.06,'#16130f');pupil.position.set(x,.2,-.61);g.add(pupil)}const beak=mesh(new T.ConeGeometry(.1,.35,4),mat('#c9933c'));beak.rotation.x=Math.PI/2;beak.position.set(0,.02,-.65);g.add(beak);return g}
function otter(){const g=animalBody('#76513b','#241a14');g.scale.set(.9,.75,1.15);const tail=mesh(new T.ConeGeometry(.22,1.7,8),mat('#654331'));tail.rotation.x=-Math.PI/2;tail.position.set(0,-.05,1.3);g.add(tail);return g}

type FieldSpec=Omit<FieldObject,'object'|'home'|'phase'|'kind'>&{kind?:'animal'|'plant';position:[number,number,number];make:()=>T.Group};
const creatureSpecs:FieldSpec[]=[
 {name:'White-tailed Deer',icon:'♞',biome:'woodland',position:[-5,1,1],make:deer,fact:'I browse on leaves and return nutrients to the soil. My alert ears also warn nearby animals when danger enters the forest.',question:'What role does the deer play here?',choices:['It recycles nutrients','It pollinates the river'],answer:0},
 {name:'Red Fox',icon:'◆',biome:'woodland',position:[10,.9,-5],make:fox,fact:'I keep small-animal populations in balance. A healthy predator can be a sign that many layers of this food web are working.',question:'Why are predators important?',choices:['They balance populations','They stop trees growing'],answer:0},
 {name:'Eastern Cottontail',icon:'♟',biome:'woodland',position:[-11,.7,-8],make:rabbit,fact:'The edge between meadow and forest gives me both food and cover. Connected habitats let me move without crossing dangerous open ground.',question:'What does the rabbit need most?',choices:['Only open pavement','Connected habitat'],answer:1},
 {name:'Brook Trout',icon:'◈',biome:'underwater',position:[2,-5,-3],make:()=>fish('#d68e50'),fact:'I need cold, clean, oxygen-rich water. Shade from streamside trees keeps this river cool enough for me.',question:'How do trees help this fish?',choices:['They warm the river','Their shade cools it'],answer:1},
 {name:'River Turtle',icon:'⬡',biome:'underwater',position:[-2,-8,4],make:turtle,fact:'I travel between water and sunny banks. Logs and stones above the water help me warm my body after a cold swim.',question:'Why does the turtle visit the bank?',choices:['To warm its body','To grow feathers'],answer:0},
 {name:'Freshwater Ray',icon:'◇',biome:'underwater',position:[6,-7,-9],make:ray,fact:'My flattened body lets me glide close to the river floor, where I find small creatures hidden in the sediment.',question:'Where does the ray search for food?',choices:['Near the river floor','Inside the clouds'],answer:0},
 {name:'Bald Eagle',icon:'⌁',biome:'sky',position:[-3,16,-4],make:()=>bird('#513e30'),fact:'Rising warm air lets me circle without constant flapping. From high above, I can read the river like a map.',question:'What helps the eagle stay aloft?',choices:['Warm rising air','Cold sinking stones'],answer:0},
 {name:'Tree Swallow',icon:'⌃',biome:'sky',position:[9,12,2],make:()=>bird('#317184'),fact:'I catch insects in flight. Wetlands below produce abundant insect life, linking the water directly to the sky.',question:'What connects this bird to the river?',choices:['Aquatic insect life','Underwater acorns'],answer:0},
 {name:'Monarch Butterfly',icon:'✣',biome:'sky',position:[-10,9,-7],make:butterfly,fact:'I navigate across a continent, but I still depend on small patches of milkweed and nectar flowers along the way.',question:'What makes migration possible?',choices:['Connected flower patches','One enormous tree'],answer:0},
 {name:'Bengal Tiger',icon:'虎',biome:'woodland',position:[13,1.2,8],make:tiger,fact:'As an apex predator, I influence where prey move and feed. Protecting my habitat also protects countless smaller species that share the same forest.',question:'Why can protecting a tiger help an ecosystem?',choices:['Its habitat shelters many species','Its stripes make trees grow'],answer:0},
 {name:'Green Frog',icon:'●',biome:'woodland',position:[5,.45,-1],make:frog,fact:'My permeable skin responds quickly to changes in water quality, so scientists can use amphibians as indicators of ecosystem health.',question:'What can frogs help reveal?',choices:['Water and habitat health','The age of the clouds'],answer:0},
 {name:'Barred Owl',icon:'◉',biome:'sky',position:[-14,8,5],make:owl,fact:'My soft-edged feathers reduce flight noise, helping me hear and approach prey after sunset.',question:'What is special about the owl’s feathers?',choices:['They make flight quieter','They glow underwater'],answer:0},
 {name:'River Otter',icon:'≈',biome:'underwater',position:[-5,-3,-8],make:otter,fact:'I need clean waterways with healthy fish populations and sheltered banks. My presence can signal a connected river ecosystem.',question:'What does an otter need?',choices:['Clean, connected waterways','Dry desert dunes'],answer:0},
 {name:'Eastern Hemlock',icon:'♲',kind:'plant',biome:'woodland',position:[-8,0,7],make:()=>tree(0,0,1.35),fact:'My evergreen canopy shades streams throughout the year, helping cold-water species while my branches shelter birds in winter.',question:'How does this tree help the stream?',choices:['It provides cooling shade','It removes all oxygen'],answer:0},
 {name:'Young Pine',icon:'♧',kind:'plant',biome:'woodland',position:[9,0,3],make:()=>tree(0,0,.9),fact:'As I grow, my roots hold soil in place and my needles add organic matter that feeds the forest floor.',question:'What do tree roots help prevent?',choices:['Soil erosion','Moonlight'],answer:0},
];
const creatures:FieldObject[]=creatureSpecs.map((spec,index)=>{const object=spec.make();object.position.fromArray(spec.position);object.traverse(child=>{child.userData.creature=index});scene.add(object);return{...spec,kind:spec.kind??'animal',object,home:object.position.clone(),phase:random()*Math.PI*2}});

const discoveries=document.querySelector('#discoveries')!;discoveries.innerHTML=creatures.map((c,i)=>`<div class="discovery" data-index="${i}" title="Undiscovered">${c.icon}</div>`).join('');
document.querySelector('#progress-count')!.textContent=`0 / ${creatures.length}`;
const found=new Set<number>();const keys=new Set<string>();let yaw=0,pitch=-.06,currentBiome:Biome='woodland',nearby=-1,dialogueOpen=false,started=false;
const velocity=new T.Vector3(),forward=new T.Vector3(),right=new T.Vector3();const clock=new T.Clock();
const raycaster=new T.Raycaster();const pointer=new T.Vector2();const personalizedCopy=new Map<number,string>();
let visitor:VisitorProfile={name:'Explorer',interests:'wildlife and ecosystems',style:'curious'};let introReady=false;
const zones:Record<Biome,{name:string;code:string;copy:string;color:string;fog:string}>={underwater:{name:'River Below',code:'Biome 01 · Freshwater',copy:'Descend through the surface and follow the lives hidden beneath the current.',color:'#176d7d',fog:'#145b68'},woodland:{name:'Woodland',code:'Biome 02 · Temperate',copy:'Follow the river, listen closely, and meet the lives that keep this forest in balance.',color:'#91c7c8',fog:'#8bb8a7'},sky:{name:'Open Sky',code:'Biome 03 · Canopy',copy:'Rise above the branches to see how wind, water, and migration connect distant habitats.',color:'#88c5df',fog:'#a9d2dc'}};
function setBiome(biome:Biome){if(currentBiome===biome)return;currentBiome=biome;const z=zones[biome];document.querySelector('#zone-name')!.textContent=z.name;document.querySelector('#zone-code')!.textContent=z.code;document.querySelector('#zone-copy')!.textContent=z.copy;world.classList.toggle('underwater',biome==='underwater');document.querySelectorAll<HTMLButtonElement>('[data-biome]').forEach(b=>b.classList.toggle('active',b.dataset.biome===biome));}
function travel(biome:Biome){const destinations:Record<Biome,T.Vector3>={underwater:new T.Vector3(0,-5,12),woodland:new T.Vector3(0,3.5,15),sky:new T.Vector3(0,14,16)};camera.position.copy(destinations[biome]);pitch=biome==='sky'?-0.12:0;setBiome(biome);renderer.domElement.requestPointerLock().catch(()=>{});}

async function getPersonalizedText(subject?:FieldObject){const response=await fetch('/api/personalize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...visitor,subject:subject?{name:subject.name,fact:subject.fact,kind:subject.kind,biome:subject.biome}:undefined})});if(!response.ok)throw new Error('Guide unavailable');return response.json() as Promise<{text:string;source:'nvidia'|'fallback';model?:string}>}
async function openDialogue(index:number){const c=creatures[index];dialogueOpen=true;if(document.pointerLockElement)document.exitPointerLock();document.querySelector('#dialogue')!.classList.add('open');document.querySelector('#dialogue-tag')!.textContent=`${c.kind==='plant'?'Flora':'Wildlife'} encounter · ${zones[c.biome].name}`;document.querySelector('#dialogue-name')!.textContent=c.name;const fact=document.querySelector('#dialogue-fact')!;fact.textContent=personalizedCopy.get(index)??'Your field guide is observing this encounter…';document.querySelector('#nim-badge')!.textContent=personalizedCopy.has(index)?'Personalized':'NVIDIA NIM · thinking';document.querySelector('#result')!.textContent='';const choices=document.querySelector('#choices')!;choices.innerHTML=c.choices.map((choice,i)=>`<button data-choice="${i}">${choice}</button>`).join('');choices.querySelectorAll<HTMLButtonElement>('button').forEach(button=>button.onclick=()=>{const selected=Number(button.dataset.choice);choices.querySelectorAll('button').forEach((b,i)=>b.classList.add(i===c.answer?'correct':i===selected?'wrong':''));const result=document.querySelector('#result')!;if(selected===c.answer){result.textContent='Field note saved · ecosystem link understood';found.add(index);const badge=document.querySelector<HTMLElement>(`.discovery[data-index="${index}"]`)!;badge.classList.add('found');badge.title=c.name;document.querySelector('#progress-count')!.textContent=`${found.size} / ${creatures.length}`;(document.querySelector('#progress-bar') as HTMLElement).style.width=`${found.size/creatures.length*100}%`;}else result.textContent='Look at the clue again and try another answer.';});if(!personalizedCopy.has(index)){try{const answer=await getPersonalizedText(c);personalizedCopy.set(index,answer.text);if(dialogueOpen&&document.querySelector('#dialogue-name')!.textContent===c.name){fact.textContent=`${answer.text} ${c.question}`;document.querySelector('#nim-badge')!.textContent=answer.source==='nvidia'?'NVIDIA NIM · personalized':'Local guide · personalized';}}catch{fact.textContent=`${c.fact} ${c.question}`;document.querySelector('#nim-badge')!.textContent='Field guide';}}else fact.textContent=`${personalizedCopy.get(index)} ${c.question}`;}
function closeDialogue(){dialogueOpen=false;document.querySelector('#dialogue')!.classList.remove('open');}
document.querySelector('#dialogue-close')!.addEventListener('click',closeDialogue);
document.querySelector('#dialogue')!.addEventListener('click',e=>{if(e.target===document.querySelector('#dialogue'))closeDialogue()});
document.querySelectorAll<HTMLButtonElement>('[data-biome]').forEach(button=>button.onclick=()=>travel(button.dataset.biome as Biome));
document.querySelector<HTMLFormElement>('#profile')!.addEventListener('submit',async event=>{event.preventDefault();if(introReady){started=true;document.querySelector('#intro')!.classList.add('hidden');return}visitor={name:(document.querySelector<HTMLInputElement>('#visitor-name')!.value.trim()||'Explorer'),interests:(document.querySelector<HTMLInputElement>('#visitor-interests')!.value.trim()||'wildlife and ecosystems'),style:document.querySelector<HTMLSelectElement>('#visitor-style')!.value};const button=document.querySelector<HTMLButtonElement>('#begin')!;button.disabled=true;button.querySelector('span')!.textContent='NVIDIA is preparing your guide…';try{const answer=await getPersonalizedText();document.querySelector('#intro-copy')!.textContent=answer.text;document.querySelector('#profile-note')!.textContent=answer.source==='nvidia'?`Generated by ${answer.model}`:'Preview mode · add NVIDIA_API_KEY for live NIM generation';document.querySelector('#ai-status')!.textContent=answer.source==='nvidia'?'NVIDIA guide online':'Local guide mode';}catch{document.querySelector('#intro-copy')!.textContent=`Welcome, ${visitor.name}. We’ll connect every discovery to ${visitor.interests} as you explore.`;document.querySelector('#profile-note')!.textContent='The live guide is unavailable, so the local field guide stepped in.';}introReady=true;button.disabled=false;button.querySelector('span')!.textContent='Enter the ecosystem';});
renderer.domElement.addEventListener('click',event=>{if(!started||dialogueOpen)return;const rect=renderer.domElement.getBoundingClientRect();if(document.pointerLockElement===renderer.domElement)pointer.set(0,0);else pointer.set(((event.clientX-rect.left)/rect.width)*2-1,-((event.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(creatures.map(c=>c.object),true).find(intersection=>intersection.object.userData.creature!==undefined);if(hit){openDialogue(Number(hit.object.userData.creature));return}renderer.domElement.requestPointerLock().catch(()=>{});});
document.addEventListener('mousemove',event=>{if(document.pointerLockElement!==renderer.domElement||dialogueOpen)return;yaw-=event.movementX*.0022;pitch=T.MathUtils.clamp(pitch-event.movementY*.002,-Math.PI/2+.04,Math.PI/2-.04)});
document.addEventListener('keydown',event=>{keys.add(event.code);if(event.code==='KeyE'&&nearby>=0&&!dialogueOpen)openDialogue(nearby);if(event.code==='Escape'&&dialogueOpen)closeDialogue()});document.addEventListener('keyup',event=>keys.delete(event.code));

let audio:globalThis.AudioContext|null=null;let soundOn=false;document.querySelector('#sound')!.addEventListener('click',()=>{soundOn=!soundOn;document.querySelector('#sound')!.textContent=soundOn?'♫':'♪';if(soundOn&&!audio){audio=new globalThis.AudioContext();const gain=audio.createGain(),filter=audio.createBiquadFilter(),osc=audio.createOscillator();osc.type='sine';osc.frequency.value=78;filter.type='lowpass';filter.frequency.value=280;gain.gain.value=.025;osc.connect(filter).connect(gain).connect(audio.destination);osc.start()}if(audio)audio[soundOn?'resume':'suspend']()});

function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2))}addEventListener('resize',resize);
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),time=clock.elapsedTime;
 camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);
 if(!dialogueOpen&&started){forward.set(-Math.sin(yaw),0,-Math.cos(yaw));right.set(Math.cos(yaw),0,-Math.sin(yaw));velocity.set(0,0,0);if(keys.has('KeyW'))velocity.add(forward);if(keys.has('KeyS'))velocity.sub(forward);if(keys.has('KeyD'))velocity.add(right);if(keys.has('KeyA'))velocity.sub(right);if(keys.has('Space'))velocity.y+=1;if(keys.has('ShiftLeft')||keys.has('ShiftRight'))velocity.y-=1;if(velocity.lengthSq())camera.position.addScaledVector(velocity.normalize(),dt*(keys.has('ControlLeft')?11:6.2));camera.position.x=T.MathUtils.clamp(camera.position.x,-29,29);camera.position.z=T.MathUtils.clamp(camera.position.z,-29,29);camera.position.y=T.MathUtils.clamp(camera.position.y,-10.4,27)}
 const biome:Biome=camera.position.y<-.8?'underwater':camera.position.y>8?'sky':'woodland';setBiome(biome);const zone=zones[biome];(scene.background as T.Color).lerp(new T.Color(zone.color),dt*1.5);(scene.fog as T.FogExp2).color.lerp(new T.Color(zone.fog),dt*1.5);(scene.fog as T.FogExp2).density=T.MathUtils.lerp((scene.fog as T.FogExp2).density,biome==='underwater'?.055:.018,dt*2);hemi.intensity=T.MathUtils.lerp(hemi.intensity,biome==='underwater'?1.15:2.3,dt*2);sun.intensity=T.MathUtils.lerp(sun.intensity,biome==='underwater'?.5:3.2,dt*2);
 creatures.forEach((c,i)=>{c.object.position.y=c.home.y+Math.sin(time*(c.biome==='woodland'?1.3:2)+c.phase)*(c.biome==='woodland'?.06:.35);if(c.biome!=='woodland')c.object.rotation.y=Math.sin(time*.35+c.phase)*.45;c.object.children.forEach((child,j)=>{if(c.biome==='sky'&&j>0)child.rotation.z+=Math.sin(time*8+c.phase)*.002})});bubbles.forEach(b=>{b.position.y+=dt*b.userData.speed;if(b.position.y>-.4)b.position.y=-10.5});riverMaterial.opacity=.74+Math.sin(time*.8)*.04;
 nearby=-1;let best=6;camera.getWorldDirection(forward);creatures.forEach((c,i)=>{const to=c.object.position.clone().sub(camera.position),distance=to.length();if(distance<best&&to.normalize().dot(forward)>.35){best=distance;nearby=i}});const hint=document.querySelector('#hint')!;hint.classList.toggle('visible',nearby>=0&&!dialogueOpen);if(nearby>=0)hint.querySelector('span')!.textContent=`Meet the ${creatures[nearby].name}`;
 document.querySelector('#altitude')!.textContent=`${camera.position.y>=0?'+':'−'}${Math.abs(camera.position.y).toFixed(1).padStart(4,'0')} m`;renderer.render(scene,camera)}animate();
