import * as T from 'three';
import './styles.css';

type Biome='underwater'|'woodland'|'sky';
type FieldObject={name:string;icon:string;kind:'animal'|'plant';biome:Biome;fact:string;question:string;choices:string[];answer:number;object:T.Group;home:T.Vector3;phase:number};
type VisitorProfile={name:string;interests:string;style:string};

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`
  <main class="world" id="world"><div class="noise"></div></main>
  <header class="brand"><div class="brand-mark">N</div><div><strong>Inside Nature</strong><small>Living field atlas · 01</small></div></header>
  <div class="top-status"><span class="ai-status" id="ai-status">Personal guide ready</span><span class="live">Ecosystem live</span><button class="sound" id="sound" aria-label="Toggle ambient sound">♪</button></div>
  <aside class="biome-card"><div class="eyebrow" id="zone-code">Biome 02 · Temperate</div><h2 id="zone-name">Woodland</h2><p id="zone-copy">Follow the river, listen closely, and meet the lives that keep this forest in balance.</p><div class="progress-label"><span>Field journal</span><span id="progress-count">0 / 0</span></div><div class="progress-track"><i id="progress-bar"></i></div><div class="discoveries" id="discoveries"></div></aside>
  <nav class="depth-nav" aria-label="Travel between biomes"><button data-biome="sky">⌁<span>Canopy & sky</span></button><i></i><button data-biome="woodland" class="active">♧<span>Forest floor</span></button><i></i><button data-biome="underwater">≋<span>Below the surface</span></button></nav>
  <div class="crosshair"></div><div class="interact-hint" id="hint"><b>E</b><span></span></div>
  <div class="controls"><div class="keys"><b class="key">W</b><b class="key">A</b><b class="key">S</b><b class="key">D</b></div><span>Move</span><div class="keys"><b class="key">Space</b><b class="key">Shift</b></div><span>Rise / descend</span><div class="keys"><b class="key">Click</b><b class="key">E</b></div><span>Discover</span></div>
  <div class="altitude"><b id="altitude">+03.5 m</b><span>Relative depth</span></div>
  <section class="intro" id="intro"><div class="intro-inner"><div class="kicker">A living world, explained for you</div><h1>Step <em>inside.</em></h1><p class="intro-copy" id="intro-copy">Tell your NVIDIA-powered field guide what sparks your curiosity. It will shape the welcome and each discovery around you.</p><form class="profile" id="profile"><label><span>What should we call you?</span><input id="visitor-name" maxlength="40" placeholder="Explorer" autocomplete="given-name"></label><label><span>What are you curious about?</span><input id="visitor-interests" maxlength="240" placeholder="food webs, big cats, climate…"></label><label><span>How should we explain?</span><select id="visitor-style"><option value="curious">Curious & vivid</option><option value="simple">Simple & concise</option><option value="scientific">Scientific</option><option value="storylike">Like a nature story</option></select></label><button class="begin" id="begin" type="submit"><span>Personalize my journey</span><i>→</i></button><small class="profile-note" id="profile-note">Works with a graceful local fallback when NVIDIA NIM is not configured.</small></form></div></section>
  <section class="dialogue" id="dialogue" aria-modal="true" role="dialog"><article class="dialogue-card"><button class="dialogue-close" id="dialogue-close" aria-label="Close">×</button><div class="dialogue-tag" id="dialogue-tag"></div><div class="dialogue-heading"><h3 id="dialogue-name"></h3><span class="nim-badge" id="nim-badge">Field guide</span></div><p id="dialogue-fact"></p><div class="choices" id="choices"></div><p class="result" id="result"></p></article></section>`;

const world=document.querySelector<HTMLElement>('#world')!;
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;world.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#91c7c8');scene.fog=new T.FogExp2('#8bb8a7',.018);
const camera=new T.PerspectiveCamera(65,innerWidth/innerHeight,.05,160);camera.position.set(0,3.5,15);

const hemi=new T.HemisphereLight(0xc6e9f2,0x23452f,2.3);scene.add(hemi);
const sun=new T.DirectionalLight(0xffe8ac,3.2);sun.position.set(-18,28,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.bias=-.0015;scene.add(sun);
const fill=new T.DirectionalLight(0xaee0ff,.5);fill.position.set(16,9,-14);scene.add(fill);
const rim=new T.DirectionalLight(0xfff1c9,.55);rim.position.set(6,4,-20);scene.add(rim);

const mat=(color:T.ColorRepresentation,roughness=.82)=>new T.MeshStandardMaterial({color,roughness,metalness:0});
const mesh=(geometry:T.BufferGeometry,material:T.Material,cast=true)=>{const value=new T.Mesh(geometry,material);value.castShadow=cast;value.receiveShadow=true;return value;};
const sphere=(r:number,color:T.ColorRepresentation,widthSeg=22,heightSeg=16)=>mesh(new T.SphereGeometry(r,widthSeg,heightSeg),mat(color));
const box=(x:number,y:number,z:number,color:T.ColorRepresentation)=>mesh(new T.BoxGeometry(x,y,z),mat(color));
const cylinder=(top:number,bottom:number,height:number,color:T.ColorRepresentation,segments=14)=>mesh(new T.CylinderGeometry(top,bottom,height,segments),mat(color));
let seed=481516;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
const range=(min:number,max:number)=>min+random()*(max-min);
const tint=(hex:string,amount:number)=>new T.Color(hex).offsetHSL(0,(random()-.5)*amount*.4,(random()-.5)*amount).getStyle();
const noise2=(x:number,z:number)=>Math.sin(x*.11)*Math.cos(z*.13)+Math.sin(x*.045+z*.08)*1.4+Math.sin((x+z)*.021)*2.1;
const swayables:{object:T.Object3D;phase:number;strength:number}[]=[];
const cloudDrifters:{object:T.Object3D;phase:number}[]=[];

// Forest floor: noise-shaded rolling terrain either side of a winding river.
function terrain(width:number,depth:number,centerX:number){const geometry=new T.PlaneGeometry(width,depth,Math.round(width*1.4),Math.round(depth*1.4));geometry.rotateX(-Math.PI/2);const position=geometry.attributes.position as T.BufferAttribute;const colors=new Float32Array(position.count*3);const c=new T.Color();for(let i=0;i<position.count;i++){const localX=position.getX(i),z=position.getZ(i),x=localX+centerX;const riverDistance=Math.abs(x-2);const rise=T.MathUtils.smoothstep(riverDistance,1.5,7);const bump=(noise2(x*.4,z*.35)*.24+noise2(x*1.3,z*1.1)*.07)*rise;position.setY(i,bump);const patch=noise2(x*.55+40,z*.55-40);const groundColor=riverDistance<4.6?'#a08652':patch>.68?'#3d6a3e':patch<-.68?'#6c9250':'#527849';c.set(groundColor).offsetHSL(0,0,noise2(x*2.2,z*2.2)*.05);colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b}geometry.setAttribute('color',new T.BufferAttribute(colors,3));geometry.computeVertexNormals();const ground=new T.Mesh(geometry,new T.MeshStandardMaterial({vertexColors:true,roughness:.96}));ground.receiveShadow=true;ground.position.set(centerX,-.05,0);scene.add(ground);return ground}
terrain(30.5,66,-19.75);terrain(26.5,66,21.75);
const riverMaterial=new T.MeshPhysicalMaterial({color:'#45baca',transparent:true,opacity:.78,roughness:.12,metalness:.05,transmission:.2,clearcoat:.6,clearcoatRoughness:.25,side:T.DoubleSide});
const river=new T.Mesh(new T.PlaneGeometry(13,66,26,44),riverMaterial);river.rotation.x=-Math.PI/2;river.position.set(2,.025,0);scene.add(river);
const riverGeometry=river.geometry as T.PlaneGeometry,riverPosition=riverGeometry.attributes.position as T.BufferAttribute;
for(const side of[-1,1]){const bank=mesh(new T.CylinderGeometry(.16,.2,65,16),mat(tint('#b08a50',.1)));bank.rotation.x=Math.PI/2;bank.position.set(2+side*6.5,.18,0);scene.add(bank);for(let i=0;i<22;i++){const pebble=sphere(.06+random()*.13,tint(random()>.5?'#8f8064':'#a89873',.16),8,6);pebble.scale.set(range(1,1.5),.6,range(1,1.4));pebble.position.set(2+side*6.5+range(-.6,.6),.05,range(-32,32));scene.add(pebble)}}
const bridge=new T.Group();for(let i=-7;i<=7;i++){const plank=box(1.1,.16,2.8,tint('#9a6338',.1));plank.position.set(i*1.02,.55,2);plank.rotation.z=Math.sin(i*.45)*.045;bridge.add(plank)}for(const z of[.85,3.15]){const rail=box(16,.12,.12,'#774729');rail.position.set(0,1.18,z);bridge.add(rail);for(let i=-7;i<=7;i++){const baluster=box(.08,.55,.08,'#6b3f24');baluster.position.set(i*1.02,.9,z);bridge.add(baluster)}}for(const x of[-7.3,7.3])for(const z of[.85,3.15]){const post=cylinder(.14,.16,1.3,'#5c3820',10);post.position.set(x,.05,z);bridge.add(post)}bridge.position.set(2,0,0);scene.add(bridge);

function foliagePuff(radius:number,color:string){return sphere(radius*range(.55,1),tint(color,.16),10,8)}
function tree(x:number,z:number,scale:number){const g=new T.Group();const lean=range(-.05,.05);const barkColor=tint('#66452d',.12);
 const flare=cylinder(.5,.62,.5,tint('#5c3f28',.08),12);flare.position.y=.28;g.add(flare);
 const trunk=cylinder(.24,.46,3.6,barkColor,12);trunk.position.y=2.05;trunk.rotation.z=lean;g.add(trunk);
 for(const[y,r,c]of[[3.4,1.65,'#2f6741'],[4.3,1.35,'#3f7b49'],[5.1,.95,'#57945a']]as[number,number,string][]){const count=Math.max(2,Math.round(r*2.6));for(let i=0;i<count;i++){const puff=foliagePuff(r,c);puff.position.set(range(-r*.55,r*.55),y+range(-r*.25,r*.25),range(-r*.55,r*.55));g.add(puff)}}
 for(let b=0;b<2;b++){const angle=b*Math.PI+range(-.3,.3);const branch=cylinder(.05,.13,range(1,1.5),barkColor,8);branch.position.set(Math.cos(angle)*.3,2.9+b*.3,Math.sin(angle)*.3);branch.rotation.z=Math.PI/2-.55;branch.rotation.y=angle;g.add(branch);for(let i=0;i<2;i++){const puff=foliagePuff(.85,'#3f7b49');puff.position.set(Math.cos(angle)*1.5+range(-.3,.3),3.2+b*.3+range(-.2,.2),Math.sin(angle)*1.5+range(-.3,.3));g.add(puff)}}
 g.position.set(x,0,z);g.scale.setScalar(scale);scene.add(g);return g}
for(let i=0;i<42;i++){let x=(random()-.5)*58,z=(random()-.5)*58;if(Math.abs(x-2)<8)x+=x<2?-8:8;tree(x,z,.72+random()*.65)}

function grassTuft(x:number,z:number){const g=new T.Group();const bladeCount=3+Math.floor(random()*3);for(let i=0;i<bladeCount;i++){const height=.5+random()*.55;const blade=mesh(new T.ConeGeometry(.06,height,6),mat(tint(random()>.4?'#6f984e':'#92aa50',.14)),false);blade.position.set(range(-.13,.13),height/2,range(-.13,.13));blade.rotation.z=range(-.2,.2);blade.rotation.y=random()*Math.PI;g.add(blade)}g.position.set(x,.02,z);scene.add(g);swayables.push({object:g,phase:random()*Math.PI*2,strength:.055});return g}
for(let i=0;i<60;i++){const x=(random()-.5)*56,z=(random()-.5)*56;if(Math.abs(x-2)<7.5)continue;grassTuft(x,z)}

function flower(x:number,z:number){const g=new T.Group();const stemHeight=.4+random()*.25;const stem=cylinder(.022,.03,stemHeight,tint('#48733d',.1),8);stem.position.y=stemHeight/2;g.add(stem);for(const side of[-1,1]){const leaf=mesh(new T.SphereGeometry(.09,8,6),mat('#4f7a3f'),false);leaf.scale.set(1.8,.25,.7);leaf.position.set(side*.09,stemHeight*.45,0);leaf.rotation.y=side*.6;g.add(leaf)}const petals=5+Math.floor(random()*3);const hue=random();const petalColor=hue>.66?'#f5d7dc':hue>.33?'#f4dd73':'#eef0e8';for(let p=0;p<petals;p++){const petal=sphere(.085,tint(petalColor,.08),8,6);petal.scale.set(1.7,.5,1);const a=p*(Math.PI*2/petals);petal.position.set(Math.cos(a)*.12,stemHeight+.02,Math.sin(a)*.12);petal.rotation.y=a;g.add(petal)}const center=sphere(.05,'#f0c23e',8,6);center.position.y=stemHeight+.03;g.add(center);g.position.set(x,0,z);scene.add(g);swayables.push({object:g,phase:random()*Math.PI*2,strength:.03});return g}
for(let i=0;i<26;i++){const x=(random()-.5)*46,z=(random()-.5)*46;if(Math.abs(x-2)<6)continue;flower(x,z)}

// Underwater world: noise-shaded seabed, rock piles, swaying kelp, and coral accents.
const seabedWall=mesh(new T.CylinderGeometry(34,35,1,48,1,true),mat('#3d7770'),false);seabedWall.position.y=-11.5;scene.add(seabedWall);
const floorGeometry=new T.CircleGeometry(34,64);floorGeometry.rotateX(-Math.PI/2);const floorPosition=floorGeometry.attributes.position as T.BufferAttribute;const floorColors=new Float32Array(floorPosition.count*3);const floorColor=new T.Color();for(let i=0;i<floorPosition.count;i++){const x=floorPosition.getX(i),z=floorPosition.getZ(i);floorPosition.setY(i,Math.sin(x*.5)*.03+noise2(x*.3,z*.3)*.05);const patch=noise2(x*.5+80,z*.5-80);floorColor.set(patch>.5?'#3d5c52':patch<-.4?'#6a6650':'#4d7167').offsetHSL(0,0,noise2(x,z)*.04);floorColors[i*3]=floorColor.r;floorColors[i*3+1]=floorColor.g;floorColors[i*3+2]=floorColor.b}floorGeometry.setAttribute('color',new T.BufferAttribute(floorColors,3));floorGeometry.computeVertexNormals();const seabedFloor=new T.Mesh(floorGeometry,new T.MeshStandardMaterial({vertexColors:true,roughness:.96}));seabedFloor.position.y=-11.5;seabedFloor.receiveShadow=true;scene.add(seabedFloor);
for(let i=0;i<26;i++){const cx=(random()-.5)*48,cz=(random()-.5)*48,count=1+Math.floor(random()*3);for(let j=0;j<count;j++){const rock=sphere(.22+random()*.6,tint(random()>.5?'#517a74':'#8c8c72',.12),10,7);rock.scale.set(range(1,1.6),range(.4,.65),range(1,1.5));rock.rotation.y=random()*Math.PI;rock.position.set(cx+range(-.5,.5),-10.75+random()*.1,cz+range(-.5,.5));scene.add(rock)}}
function weed(x:number,z:number){const g=new T.Group();const segments=3+Math.floor(random()*3);const color=tint(random()>.5?'#2d8771':'#6aa764',.12);let y=0;for(let i=0;i<segments;i++){const h=.5+random()*.4;const blade=mesh(new T.ConeGeometry(Math.max(.02,.09-i*.015),h,7),mat(color),false);blade.position.y=y+h/2;blade.rotation.z=range(-.14,.14);g.add(blade);y+=h*.85}g.position.set(x,-10+random()*.3,z);scene.add(g);swayables.push({object:g,phase:random()*Math.PI*2,strength:.1});return g}
for(let i=0;i<38;i++)weed((random()-.5)*45,(random()-.5)*45);
function coral(x:number,z:number){const g=new T.Group();const baseColor=tint(random()>.5?'#e0704f':'#d94f7a',.14);const branches=3+Math.floor(random()*3);for(let i=0;i<branches;i++){const h=.4+random()*.6;const branch=cylinder(.03,.08,h,baseColor,7);branch.position.set(range(-.2,.2),h/2,range(-.2,.2));branch.rotation.z=range(-.5,.5);branch.rotation.x=range(-.5,.5);g.add(branch)}g.position.set(x,-10.9,z);scene.add(g)}
for(let i=0;i<15;i++)coral((random()-.5)*40,(random()-.5)*40);
const bubbles:T.Mesh[]=[];for(let i=0;i<48;i++){const bubble=new T.Mesh(new T.SphereGeometry(.04+random()*.09,10,7),new T.MeshBasicMaterial({color:'#c8f5ed',transparent:true,opacity:.5,wireframe:true}));bubble.position.set((random()-.5)*45,-10+random()*9,(random()-.5)*45);bubble.userData.speed=.25+random()*.5;bubbles.push(bubble);scene.add(bubble)}

// Sky landmarks: puffier, drifting clouds with per-puff shading.
for(let i=0;i<15;i++){const cloud=new T.Group();const puffCount=5+Math.floor(random()*4);for(let j=0;j<puffCount;j++){const puff=new T.Mesh(new T.SphereGeometry(1+range(-.25,.65),12,8),new T.MeshStandardMaterial({color:tint('#fff7df',.05),roughness:1,transparent:true,opacity:range(.78,.94)}));puff.scale.y=.45+random()*.2;puff.position.set(j*1.3+range(-.5,.5),random()*.65,range(-.6,.6));cloud.add(puff)}cloud.position.set((random()-.5)*60,12+random()*15,(random()-.5)*60);cloud.scale.setScalar(range(.8,1.35));scene.add(cloud);cloudDrifters.push({object:cloud,phase:random()*Math.PI*2})}

function animalBody(color:string,accent:string){const g=new T.Group();const body=sphere(.65,color,22,16);body.scale.set(1.35,.78,.72);body.rotation.y=Math.PI/2;g.add(body);const neck=cylinder(.28,.36,.5,tint(color,.08),10);neck.position.set(0,.3,-.62);neck.rotation.x=.7;g.add(neck);const head=sphere(.43,color,20,14);head.position.set(0,.42,-.85);g.add(head);const snout=sphere(.24,tint(color,.08),14,10);snout.scale.set(1,.75,1.3);snout.position.set(0,.3,-1.18);g.add(snout);const eye=sphere(.055,'#101b17',8,6);eye.position.set(.3,.5,-1.05);g.add(eye);const eye2=eye.clone();eye2.position.x=-.3;g.add(eye2);const nose=sphere(.09,accent,8,6);nose.position.set(0,.28,-1.32);g.add(nose);return g}
function deer(){const g=animalBody('#a86a35','#33251d');g.scale.setScalar(.85);for(const x of[-.4,.4])for(const z of[-.3,.35]){const leg=cylinder(.07,.09,1.2,tint('#74472d',.08),8);leg.position.set(x,-.72,z);g.add(leg);const paw=sphere(.08,'#2c2018',6,5);paw.position.set(x,-1.3,z);g.add(paw)}for(const x of[-.23,.23]){const antler=cylinder(.035,.055,.8,'#d2b27b',6);antler.position.set(x,1,-.85);antler.rotation.z=x*1.5;g.add(antler);const tine=cylinder(.02,.03,.32,'#d2b27b',5);tine.position.set(x+(x<0?-.14:.14),1.28,-.7);tine.rotation.z=x*2.2;g.add(tine)}return g}
function fox(){const g=animalBody('#c55e32','#342018');for(const x of[-.35,.35])for(const z of[-.25,.3]){const leg=cylinder(.06,.075,.9,tint('#9e432b',.08),8);leg.position.set(x,-.65,z);g.add(leg);const paw=sphere(.07,'#241610',6,5);paw.position.set(x,-1.08,z);g.add(paw)}for(const x of[-.42,.42]){const ear=mesh(new T.ConeGeometry(.2,.55,7),mat('#9e432b'));ear.position.set(x,.9,-.77);g.add(ear);const earInner=mesh(new T.ConeGeometry(.11,.32,6),mat('#2c1a12'));earInner.position.set(x,.85,-.7);g.add(earInner)}const tail=mesh(new T.ConeGeometry(.35,1.8,10),mat('#d87542'));tail.rotation.x=-Math.PI/2;tail.position.set(0,.15,1.25);g.add(tail);const tailTip=sphere(.2,'#f4ede2',8,6);tailTip.position.set(0,.15,2.05);g.add(tailTip);return g}
function rabbit(){const g=animalBody('#9b8f7d','#594b42');g.scale.setScalar(.65);for(const x of[-.28,.28])for(const z of[-.15,.2]){const leg=cylinder(.05,.06,.5,tint('#7d7264',.08),7);leg.position.set(x,-.42,z);g.add(leg)}for(const x of[-.2,.2]){const ear=sphere(.18,'#a79c8c',10,8);ear.scale.set(1,2.8,.6);ear.position.set(x,1,-.72);g.add(ear);const earInner=sphere(.11,'#c9a99a',8,6);earInner.scale.set(1,2.6,.5);earInner.position.set(x,1,-.66);g.add(earInner)}const tail=sphere(.15,'#f4f0e6',8,6);tail.position.set(0,.1,.9);g.add(tail);return g}
function fish(color:string){const g=new T.Group();const body=sphere(.62,color,18,14);body.scale.set(1.55,.72,.45);g.add(body);const tail=mesh(new T.ConeGeometry(.55,1,4),mat(color));tail.rotation.z=-Math.PI/2;tail.position.x=-1.15;g.add(tail);const dorsal=mesh(new T.ConeGeometry(.3,.5,4),mat(tint(color,.15)));dorsal.rotation.x=Math.PI;dorsal.position.set(0,.42,0);g.add(dorsal);for(const side of[-1,1]){const fin=mesh(new T.ConeGeometry(.18,.4,4),mat(tint(color,.1)));fin.rotation.z=side*1.1;fin.position.set(.15,-.05,side*.3);g.add(fin)}const eye=sphere(.07,'#101b17',8,6);eye.position.set(.68,.2,.35);g.add(eye);return g}
function turtle(){const g=new T.Group();const shell=sphere(.7,'#527945',16,12);shell.scale.set(1.25,.45,1);g.add(shell);for(let i=0;i<5;i++){const scute=sphere(.14,tint('#3f5c37',.1),8,6);scute.scale.set(1,.4,1);const a=(i/5)*Math.PI*2;scute.position.set(Math.cos(a)*.4,.28,Math.sin(a)*.55);g.add(scute)}const head=sphere(.3,'#7aa068',10,8);head.position.x=1;g.add(head);for(const z of[-.65,.65])for(const x of[-.45,.45]){const fin=mesh(new T.ConeGeometry(.18,.65,6),mat('#71935f'));fin.rotation.z=Math.PI/2;fin.position.set(x,0,z);g.add(fin)}return g}
function ray(){const g=new T.Group();const wing=mesh(new T.SphereGeometry(.9,20,10),mat('#487b84'));wing.scale.set(1.7,.16,1);g.add(wing);for(let i=0;i<6;i++){const spot=sphere(.05,'#c9e9e5',6,5);spot.position.set(range(-1,1),.09,range(-.7,.7));g.add(spot)}const tail=cylinder(.03,.07,2.3,'#365e65',8);tail.rotation.z=Math.PI/2;tail.position.x=-1.6;g.add(tail);return g}
function wingBlade(rootRadius:number,tipRadius:number,length:number,color:T.ColorRepresentation){const geometry=new T.CylinderGeometry(rootRadius,tipRadius,length,10);geometry.rotateZ(Math.PI/2);geometry.scale(1,1,.3);return mesh(geometry,mat(color))}
function bird(color:string){const g=new T.Group();const body=sphere(.35,color,16,12);body.scale.set(.75,.65,1.45);g.add(body);const head=sphere(.22,color,12,10);head.position.z=-.95;g.add(head);for(const side of[-1,1]){const wing=wingBlade(.46,.05,1.6,tint(color,.08));if(side<0)wing.rotation.y=Math.PI;wing.rotation.x=side*.15;wing.position.set(side*1,.05,.05);g.add(wing);const covert=wingBlade(.26,.03,.7,tint(color,.15));if(side<0)covert.rotation.y=Math.PI;covert.position.set(side*.35,.13,.15);g.add(covert)}const tail=mesh(new T.ConeGeometry(.3,.9,4),mat(tint(color,.12)));tail.rotation.x=Math.PI/2;tail.position.z=.85;g.add(tail);const beak=mesh(new T.ConeGeometry(.1,.42,6),mat('#e5b047'));beak.rotation.x=Math.PI/2;beak.position.z=-1.15;g.add(beak);return g}
function butterfly(){const g=new T.Group();const body=cylinder(.06,.08,.65,'#2c211b',8);body.rotation.x=Math.PI/2;g.add(body);for(const side of[-1,1]){const wing=sphere(.38,side<0?'#e5903c':'#efb24c',12,8);wing.scale.set(.22,1,1.2);wing.position.x=side*.27;g.add(wing);const spot=sphere(.09,'#2c211b',8,6);spot.scale.set(.15,.5,.5);spot.position.set(side*.32,.15,.25);g.add(spot)}for(const side of[-1,1]){const antenna=cylinder(.008,.008,.3,'#2c211b',4);antenna.position.set(side*.05,.12,-.32);antenna.rotation.x=-.5;antenna.rotation.z=side*.3;g.add(antenna)}return g}
function tiger(){const g=animalBody('#d97827','#26180f');g.scale.setScalar(1.18);for(const x of[-.5,.5])for(const z of[-.3,.35]){const leg=cylinder(.1,.13,1.25,'#d97827',8);leg.position.set(x,-.78,z);g.add(leg);const paw=sphere(.12,'#f4ede2',7,6);paw.position.set(x,-1.42,z);g.add(paw)}for(let i=-2;i<=2;i++){const stripe=box(.07,.48,.72,'#2b2019');stripe.position.set(i*.25,.28,.05);stripe.rotation.z=i*.1;g.add(stripe)}for(const x of[-.27,.27]){const ear=mesh(new T.ConeGeometry(.2,.45,7),mat('#2b2019'));ear.position.set(x,.88,-.82);g.add(ear)}return g}
function frog(){const g=new T.Group();const body=sphere(.42,'#5d9b48',16,12);body.scale.set(1,.65,1.15);g.add(body);for(const x of[-.28,.28]){const eye=sphere(.14,'#9bc66c',10,8);eye.position.set(x,.34,-.25);g.add(eye);const pupil=sphere(.05,'#172418',6,5);pupil.position.set(x,.38,-.37);g.add(pupil)}for(const x of[-.5,.5]){const leg=box(.55,.12,.16,'#4f873e');leg.position.set(x,-.18,.22);g.add(leg);for(let t=0;t<3;t++){const toe=box(.16,.06,.08,'#4f873e');toe.position.set(x+(x<0?-.28:.28),-.2,.28+t*.13-.13);g.add(toe)}}for(const x of[-.32,.32]){const arm=cylinder(.06,.07,.3,'#5d9b48',6);arm.rotation.z=Math.PI/2;arm.position.set(x,.02,-.28);g.add(arm)}return g}
function owl(){const g=new T.Group();const body=sphere(.55,'#8b7257',18,14);body.scale.set(.8,1.2,.72);g.add(body);for(const side of[-1,1]){const wing=mesh(new T.SphereGeometry(.32,10,8),mat(tint('#6f5a41',.1)));wing.scale.set(.4,1,.8);wing.position.set(side*.5,-.05,0);g.add(wing)}for(const x of[-.2,.2]){const eye=sphere(.15,'#e6c35a',10,8);eye.position.set(x,.2,-.48);g.add(eye);const pupil=sphere(.06,'#16130f',8,6);pupil.position.set(x,.2,-.61);g.add(pupil);const tuft=mesh(new T.ConeGeometry(.06,.22,5),mat('#5c4a35'));tuft.position.set(x*1.3,.75,-.3);tuft.rotation.z=x*1.5;g.add(tuft)}const beak=mesh(new T.ConeGeometry(.1,.35,6),mat('#c9933c'));beak.rotation.x=Math.PI/2;beak.position.set(0,.02,-.65);g.add(beak);return g}
function otter(){const g=animalBody('#76513b','#241a14');g.scale.set(.9,.75,1.15);const tail=mesh(new T.ConeGeometry(.22,1.7,8),mat('#654331'));tail.rotation.x=-Math.PI/2;tail.position.set(0,-.05,1.3);g.add(tail);for(const x of[-.3,.3])for(const z of[-.2,.25]){const leg=cylinder(.07,.08,.5,tint('#5c4230',.08),7);leg.position.set(x,-.55,z);g.add(leg)}return g}

type FieldSpec=Omit<FieldObject,'object'|'home'|'phase'|'kind'>&{kind?:'animal'|'plant';position:[number,number,number];make:()=>T.Group};
const creatureSpecs:FieldSpec[]=[
 {name:'White-tailed Deer',icon:'♞',biome:'woodland',position:[-5,1,1],make:deer,fact:'I browse on leaves and return nutrients to the soil. My alert ears also warn nearby animals when danger enters the forest.',question:'What role does the deer play here?',choices:['It recycles nutrients','It pollinates the river'],answer:0},
 {name:'Red Fox',icon:'◆',biome:'woodland',position:[10,.9,-5],make:fox,fact:'I keep small-animal populations in balance. A healthy predator can be a sign that many layers of this food web are working.',question:'Why are predators important?',choices:['They balance populations','They stop trees growing'],answer:0},
 {name:'Eastern Cottontail',icon:'♟',biome:'woodland',position:[-11,.7,-8],make:rabbit,fact:'The edge between meadow and forest gives me both food and cover. Connected habitats let me move without crossing dangerous open ground.',question:'What does the rabbit need most?',choices:['Only open pavement','Connected habitat'],answer:1},
 {name:'Brook Trout',icon:'◈',biome:'underwater',position:[2,-5,-3],make:()=>fish('#d68e50'),fact:'I need cold, clean, oxygen-rich water. Shade from streamside trees keeps this river cool enough for me.',question:'How do trees help this fish?',choices:['They warm the river','Their shade cools it'],answer:1},
 {name:'River Turtle',icon:'⬡',biome:'underwater',position:[-2,-8,4],make:turtle,fact:'I travel between water and sunny banks. Logs and stones above the water help me warm my body after a cold swim.',question:'Why does the turtle visit the bank?',choices:['To warm its body','To grow feathers'],answer:0},
 {name:'Freshwater Ray',icon:'◇',biome:'underwater',position:[6,-7,-9],make:ray,fact:'My flattened body lets me glide close to the river floor, where I find small creatures hidden in the sediment.',question:'Where does the ray search for food?',choices:['Near the river floor','Inside the clouds'],answer:0},
 {name:'Bald Eagle',icon:'⌁',biome:'sky',position:[-3,16,-4],make:()=>bird('#513e30'),fact:'Rising warm air lets me circle without constant flapping. From high above, I can read the river like a map.',question:'What helps the eagle stay aloft?',choices:['Warm rising air','Cold sinking stones'],answer:0},
 {name:'Tree Swallow',icon:'⌃',biome:'sky',position:[9,12,2],make:()=>bird('#317184'),fact:'I catch insects in flight. Wetlands below produce abundant insect life, linking the water directly to the sky.',question:'What connects this bird to the river?',choices:['Aquatic insect life','Underwater acorns'],answer:0},
 {name:'Monarch Butterfly',icon:'✣',biome:'sky',position:[-10,9,-7],make:butterfly,fact:'I navigate across a continent, but I still depend on small patches of milkweed and nectar flowers along the way.',question:'What makes migration possible?',choices:['Connected flower patches','One enormous tree'],answer:0},
 {name:'Bengal Tiger',icon:'虎',biome:'woodland',position:[13,1.2,8],make:tiger,fact:'As an apex predator, I influence where prey move and feed. Protecting my habitat also protects countless smaller species that share the same forest.',question:'Why can protecting a tiger help an ecosystem?',choices:['Its habitat shelters many species','Its stripes make trees grow'],answer:0},
 {name:'Green Frog',icon:'●',biome:'woodland',position:[5,.45,-1],make:frog,fact:'My permeable skin responds quickly to changes in water quality, so scientists can use amphibians as indicators of ecosystem health.',question:'What can frogs help reveal?',choices:['Water and habitat health','The age of the clouds'],answer:0},
 {name:'Barred Owl',icon:'◉',biome:'sky',position:[-14,8,5],make:owl,fact:'My soft-edged feathers reduce flight noise, helping me hear and approach prey after sunset.',question:'What is special about the owl’s feathers?',choices:['They make flight quieter','They glow underwater'],answer:0},
 {name:'River Otter',icon:'≈',biome:'underwater',position:[-5,-3,-8],make:otter,fact:'I need clean waterways with healthy fish populations and sheltered banks. My presence can signal a connected river ecosystem.',question:'What does an otter need?',choices:['Clean, connected waterways','Dry desert dunes'],answer:0},
 {name:'Eastern Hemlock',icon:'♲',kind:'plant',biome:'woodland',position:[-8,0,7],make:()=>tree(0,0,1.35),fact:'My evergreen canopy shades streams throughout the year, helping cold-water species while my branches shelter birds in winter.',question:'How does this tree help the stream?',choices:['It provides cooling shade','It removes all oxygen'],answer:0},
 {name:'Young Pine',icon:'♧',kind:'plant',biome:'woodland',position:[9,0,3],make:()=>tree(0,0,.9),fact:'As I grow, my roots hold soil in place and my needles add organic matter that feeds the forest floor.',question:'What do tree roots help prevent?',choices:['Soil erosion','Moonlight'],answer:0},
];
const creatures:FieldObject[]=creatureSpecs.map((spec,index)=>{const object=spec.make();object.position.fromArray(spec.position);object.traverse(child=>{child.userData.creature=index});scene.add(object);return{...spec,kind:spec.kind??'animal',object,home:object.position.clone(),phase:random()*Math.PI*2}});

const discoveries=document.querySelector('#discoveries')!;discoveries.innerHTML=creatures.map((c,i)=>`<div class="discovery" data-index="${i}" title="Undiscovered">${c.icon}</div>`).join('');
document.querySelector('#progress-count')!.textContent=`0 / ${creatures.length}`;
const found=new Set<number>();const keys=new Set<string>();let yaw=0,pitch=-.06,currentBiome:Biome='woodland',nearby=-1,dialogueOpen=false,started=false;
const velocity=new T.Vector3(),forward=new T.Vector3(),right=new T.Vector3();const clock=new T.Clock();
const raycaster=new T.Raycaster();const pointer=new T.Vector2();const personalizedCopy=new Map<number,string>();
let visitor:VisitorProfile={name:'Explorer',interests:'wildlife and ecosystems',style:'curious'};let introReady=false;
const zones:Record<Biome,{name:string;code:string;copy:string;color:string;fog:string}>={underwater:{name:'River Below',code:'Biome 01 · Freshwater',copy:'Descend through the surface and follow the lives hidden beneath the current.',color:'#176d7d',fog:'#145b68'},woodland:{name:'Woodland',code:'Biome 02 · Temperate',copy:'Follow the river, listen closely, and meet the lives that keep this forest in balance.',color:'#91c7c8',fog:'#8bb8a7'},sky:{name:'Open Sky',code:'Biome 03 · Canopy',copy:'Rise above the branches to see how wind, water, and migration connect distant habitats.',color:'#88c5df',fog:'#a9d2dc'}};
function setBiome(biome:Biome){if(currentBiome===biome)return;currentBiome=biome;const z=zones[biome];document.querySelector('#zone-name')!.textContent=z.name;document.querySelector('#zone-code')!.textContent=z.code;document.querySelector('#zone-copy')!.textContent=z.copy;world.classList.toggle('underwater',biome==='underwater');document.querySelectorAll<HTMLButtonElement>('[data-biome]').forEach(b=>b.classList.toggle('active',b.dataset.biome===biome));}
function travel(biome:Biome){const destinations:Record<Biome,T.Vector3>={underwater:new T.Vector3(0,-5,12),woodland:new T.Vector3(0,3.5,15),sky:new T.Vector3(0,14,16)};camera.position.copy(destinations[biome]);pitch=biome==='sky'?-0.12:0;setBiome(biome);renderer.domElement.requestPointerLock().catch(()=>{});}

async function getPersonalizedText(subject?:FieldObject){const response=await fetch('/api/personalize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...visitor,subject:subject?{name:subject.name,fact:subject.fact,kind:subject.kind,biome:subject.biome}:undefined})});if(!response.ok)throw new Error('Guide unavailable');return response.json() as Promise<{text:string;source:'nvidia'|'fallback';model?:string}>}
async function openDialogue(index:number){const c=creatures[index];dialogueOpen=true;if(document.pointerLockElement)document.exitPointerLock();document.querySelector('#dialogue')!.classList.add('open');document.querySelector('#dialogue-tag')!.textContent=`${c.kind==='plant'?'Flora':'Wildlife'} encounter · ${zones[c.biome].name}`;document.querySelector('#dialogue-name')!.textContent=c.name;const fact=document.querySelector('#dialogue-fact')!;fact.textContent=personalizedCopy.get(index)??'Your field guide is observing this encounter…';document.querySelector('#nim-badge')!.textContent=personalizedCopy.has(index)?'Personalized':'NVIDIA NIM · thinking';document.querySelector('#result')!.textContent='';const choices=document.querySelector('#choices')!;choices.innerHTML=c.choices.map((choice,i)=>`<button data-choice="${i}">${choice}</button>`).join('');choices.querySelectorAll<HTMLButtonElement>('button').forEach(button=>button.onclick=()=>{const selected=Number(button.dataset.choice);choices.querySelectorAll('button').forEach((b,i)=>b.classList.add(i===c.answer?'correct':i===selected?'wrong':''));const result=document.querySelector('#result')!;if(selected===c.answer){result.textContent='Field note saved · ecosystem link understood';found.add(index);const badge=document.querySelector<HTMLElement>(`.discovery[data-index="${index}"]`)!;badge.classList.add('found');badge.title=c.name;document.querySelector('#progress-count')!.textContent=`${found.size} / ${creatures.length}`;(document.querySelector('#progress-bar') as HTMLElement).style.width=`${found.size/creatures.length*100}%`;}else result.textContent='Look at the clue again and try another answer.';});if(!personalizedCopy.has(index)){try{const answer=await getPersonalizedText(c);personalizedCopy.set(index,answer.text);if(dialogueOpen&&document.querySelector('#dialogue-name')!.textContent===c.name){fact.textContent=`${answer.text} ${c.question}`;document.querySelector('#nim-badge')!.textContent=answer.source==='nvidia'?'NVIDIA NIM · personalized':'Local guide · personalized';}}catch{fact.textContent=`${c.fact} ${c.question}`;document.querySelector('#nim-badge')!.textContent='Field guide';}}else fact.textContent=`${personalizedCopy.get(index)} ${c.question}`;}
function closeDialogue(){dialogueOpen=false;document.querySelector('#dialogue')!.classList.remove('open');}
document.querySelector('#dialogue-close')!.addEventListener('click',closeDialogue);
document.querySelector('#dialogue')!.addEventListener('click',e=>{if(e.target===document.querySelector('#dialogue'))closeDialogue()});
document.querySelectorAll<HTMLButtonElement>('[data-biome]').forEach(button=>button.onclick=()=>travel(button.dataset.biome as Biome));
document.querySelector<HTMLFormElement>('#profile')!.addEventListener('submit',async event=>{event.preventDefault();if(introReady){started=true;document.querySelector('#intro')!.classList.add('hidden');return}visitor={name:(document.querySelector<HTMLInputElement>('#visitor-name')!.value.trim()||'Explorer'),interests:(document.querySelector<HTMLInputElement>('#visitor-interests')!.value.trim()||'wildlife and ecosystems'),style:document.querySelector<HTMLSelectElement>('#visitor-style')!.value};const button=document.querySelector<HTMLButtonElement>('#begin')!;button.disabled=true;button.querySelector('span')!.textContent='NVIDIA is preparing your guide…';try{const answer=await getPersonalizedText();document.querySelector('#intro-copy')!.textContent=answer.text;document.querySelector('#profile-note')!.textContent=answer.source==='nvidia'?`Generated by ${answer.model}`:'Preview mode · add NVIDIA_API_KEY for live NIM generation';document.querySelector('#ai-status')!.textContent=answer.source==='nvidia'?'NVIDIA guide online':'Local guide mode';}catch{document.querySelector('#intro-copy')!.textContent=`Welcome, ${visitor.name}. We’ll connect every discovery to ${visitor.interests} as you explore.`;document.querySelector('#profile-note')!.textContent='The live guide is unavailable, so the local field guide stepped in.';}introReady=true;button.disabled=false;button.querySelector('span')!.textContent='Enter the ecosystem';});
renderer.domElement.addEventListener('click',event=>{if(!started||dialogueOpen)return;const rect=renderer.domElement.getBoundingClientRect();if(document.pointerLockElement===renderer.domElement)pointer.set(0,0);else pointer.set(((event.clientX-rect.left)/rect.width)*2-1,-((event.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(creatures.map(c=>c.object),true).find(intersection=>intersection.object.userData.creature!==undefined);if(hit){openDialogue(Number(hit.object.userData.creature));return}renderer.domElement.requestPointerLock().catch(()=>{});});
document.addEventListener('mousemove',event=>{if(document.pointerLockElement!==renderer.domElement||dialogueOpen)return;yaw-=event.movementX*.0022;pitch=T.MathUtils.clamp(pitch-event.movementY*.002,-Math.PI/2+.04,Math.PI/2-.04)});
document.addEventListener('keydown',event=>{keys.add(event.code);if(event.code==='KeyE'&&nearby>=0&&!dialogueOpen)openDialogue(nearby);if(event.code==='Escape'&&dialogueOpen)closeDialogue()});document.addEventListener('keyup',event=>keys.delete(event.code));

let audio:globalThis.AudioContext|null=null;let soundOn=false;document.querySelector('#sound')!.addEventListener('click',()=>{soundOn=!soundOn;document.querySelector('#sound')!.textContent=soundOn?'♫':'♪';if(soundOn&&!audio){audio=new globalThis.AudioContext();const gain=audio.createGain(),filter=audio.createBiquadFilter(),osc=audio.createOscillator();osc.type='sine';osc.frequency.value=78;filter.type='lowpass';filter.frequency.value=280;gain.gain.value=.025;osc.connect(filter).connect(gain).connect(audio.destination);osc.start()}if(audio)audio[soundOn?'resume':'suspend']()});

function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2))}addEventListener('resize',resize);
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),time=clock.elapsedTime;
 camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);
 if(!dialogueOpen&&started){forward.set(-Math.sin(yaw),0,-Math.cos(yaw));right.set(Math.cos(yaw),0,-Math.sin(yaw));velocity.set(0,0,0);if(keys.has('KeyW'))velocity.add(forward);if(keys.has('KeyS'))velocity.sub(forward);if(keys.has('KeyD'))velocity.add(right);if(keys.has('KeyA'))velocity.sub(right);if(keys.has('Space'))velocity.y+=1;if(keys.has('ShiftLeft')||keys.has('ShiftRight'))velocity.y-=1;if(velocity.lengthSq())camera.position.addScaledVector(velocity.normalize(),dt*(keys.has('ControlLeft')?11:6.2));camera.position.x=T.MathUtils.clamp(camera.position.x,-29,29);camera.position.z=T.MathUtils.clamp(camera.position.z,-29,29);camera.position.y=T.MathUtils.clamp(camera.position.y,-10.4,27)}
 const biome:Biome=camera.position.y<-.8?'underwater':camera.position.y>8?'sky':'woodland';setBiome(biome);const zone=zones[biome];(scene.background as T.Color).lerp(new T.Color(zone.color),dt*1.5);(scene.fog as T.FogExp2).color.lerp(new T.Color(zone.fog),dt*1.5);(scene.fog as T.FogExp2).density=T.MathUtils.lerp((scene.fog as T.FogExp2).density,biome==='underwater'?.055:.018,dt*2);hemi.intensity=T.MathUtils.lerp(hemi.intensity,biome==='underwater'?1.15:2.3,dt*2);sun.intensity=T.MathUtils.lerp(sun.intensity,biome==='underwater'?.5:3.2,dt*2);
 creatures.forEach((c,i)=>{c.object.position.y=c.home.y+Math.sin(time*(c.biome==='woodland'?1.3:2)+c.phase)*(c.biome==='woodland'?.06:.35);if(c.biome!=='woodland')c.object.rotation.y=Math.sin(time*.35+c.phase)*.45;c.object.children.forEach((child,j)=>{if(c.biome==='sky'&&j>0)child.rotation.z+=Math.sin(time*8+c.phase)*.002})});bubbles.forEach(b=>{b.position.y+=dt*b.userData.speed;if(b.position.y>-.4)b.position.y=-10.5});riverMaterial.opacity=.74+Math.sin(time*.8)*.04;
 for(let i=0;i<riverPosition.count;i++){const x=riverPosition.getX(i),y=riverPosition.getY(i);riverPosition.setZ(i,Math.sin(x*.6+time*1.4)*.03+Math.sin(y*.35+time*.9)*.022)}riverPosition.needsUpdate=true;riverGeometry.computeVertexNormals();
 swayables.forEach(s=>{s.object.rotation.z=Math.sin(time*1.6+s.phase)*s.strength});
 cloudDrifters.forEach(cd=>{cd.object.position.x+=dt*.18;if(cd.object.position.x>34)cd.object.position.x=-34;cd.object.position.y+=Math.sin(time*.15+cd.phase)*.003});
 nearby=-1;let best=6;camera.getWorldDirection(forward);creatures.forEach((c,i)=>{const to=c.object.position.clone().sub(camera.position),distance=to.length();if(distance<best&&to.normalize().dot(forward)>.35){best=distance;nearby=i}});const hint=document.querySelector('#hint')!;hint.classList.toggle('visible',nearby>=0&&!dialogueOpen);if(nearby>=0)hint.querySelector('span')!.textContent=`Meet the ${creatures[nearby].name}`;
 document.querySelector('#altitude')!.textContent=`${camera.position.y>=0?'+':'−'}${Math.abs(camera.position.y).toFixed(1).padStart(4,'0')} m`;renderer.render(scene,camera)}animate();
